# Basic Information 
title: Haobo Zhao
position: MSE Mechanical Engineering Student
affiliation: Johns Hopkins University
affiliation_link: https://www.jhu.edu/
# affiliation_logo: ./assets/img/whiting.logo.horizontal.white.svg
# affiliation_logo: ./assets/img/wse.svg
email: hzhao67@jhu.edu

# Search Engine Optimization (SEO)
keywords: Haobo Zhao, computational fluid dynamics, CFD, biofluid mechanics, pancreatic duct flow, Johns Hopkins University
url: https://zhbalex.github.io
description: Haobo Zhao is a mechanical engineering master's student at Johns Hopkins University working on computational fluid dynamics, biofluid mechanics, pancreatic duct flow, and scientific computing.

# The option is used to enable the Illinois template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?view_op=list_works&hl=en&hl=en&user=Itqka-wAAAAJ
github_link: https://github.com/ZHBALEX/
linkedin: https://www.linkedin.com/in/haobo-zhao-035529229
cv_link: /CV/CV_Haobo_Zhao_2024.pdf

# Images 
# avatar: https://img.yliu.me/avatar_new.jpg
# avatar: https://github.com/ZHBALEX/Haobo_Zhao_Personal_Information/blob/114d5d5d77d5de82504b5dfa84815b078a3b8691/photo_me/HaoboZhao.jpg
# avatar: zhb_personal/HaoboZhao.jpg
# avatar: https://github.com/ZHBALEX/Zhbalex.GitHub.io/zhb_personal/HaoboZhao_livi.jpg
avatar: /zhb_personal/HaoboZhao.jpg
# right click of the image on github page to copy address

# Footnotes
footnote: Feel free to use my website's source code.
footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: CJD8XwsJhSyQ6sbsU-Gw0cNcUlbah7KW3xvHN2QlwW0

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
  - serve-local.ps1
  - compile-cv.ps1
  - start-server.ps1
  - stop-server.ps1
  - jekyll_server.log
  - jekyll_server.err.log
  - jekyll_server.pid
