"""Fetch Google Scholar publications and generate site/CV publication files."""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = REPO_ROOT / "_config.yml"
SITE_DATA_PATH = REPO_ROOT / "_data" / "scholar_publications.yml"
CV_TEX_PATH = REPO_ROOT / "CV" / "generated_publications.tex"
RAW_JSON_PATH = REPO_ROOT / "google_scholar_crawler" / "results" / "gs_data.json"

IN_PREPARATION: list[str] = []


def read_scholar_id() -> str:
    text = CONFIG_PATH.read_text(encoding="utf-8")
    match = re.search(r"google_scholar:\s*(.+)", text)
    if not match:
        raise RuntimeError("Missing google_scholar in _config.yml")
    url = match.group(1).strip().strip('"').strip("'")
    user_match = re.search(r"[?&]user=([^&\s]+)", url)
    if not user_match:
        raise RuntimeError("Could not find a user=... Scholar ID in google_scholar")
    return user_match.group(1)


def latex_escape(text: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in text)


def format_authors(authors: str) -> str:
    parts = [part.strip() for part in re.split(r"\s+and\s+", authors) if part.strip()]
    if len(parts) <= 1:
        return authors
    if len(parts) == 2:
        return f"{parts[0]} and {parts[1]}"
    return f"{', '.join(parts[:-1])}, and {parts[-1]}"


def yaml_scalar(value: Any) -> str:
    if value is None:
        return '""'
    if isinstance(value, (int, float)):
        return str(value)
    text = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{text}"'


def normalize_publication(pub: dict[str, Any]) -> dict[str, Any]:
    bib = pub.get("bib", {}) or {}
    title = bib.get("title") or pub.get("title") or "Untitled"
    year = bib.get("pub_year") or bib.get("year") or ""
    venue = bib.get("venue") or bib.get("journal") or bib.get("conference") or bib.get("citation") or ""
    authors = bib.get("author") or bib.get("authors") or ""
    url = pub.get("pub_url") or pub.get("eprint_url") or pub.get("url") or ""
    title = re.sub(r":\s*H\.\s*Zhao et al\.?$", "", str(title).strip())
    if not authors:
        authors = "Haobo Zhao et al."
    authors = format_authors(str(authors))

    return {
        "title": title,
        "authors": str(authors).strip(),
        "year": str(year).strip(),
        "venue": str(venue).strip(),
        "citations": int(pub.get("num_citations") or 0),
        "url": str(url).strip(),
        "source": "google_scholar",
    }


def fetch_scholar(author_id: str) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    from scholarly import scholarly

    author = scholarly.search_author_id(author_id)
    scholarly.fill(author, sections=["basics", "indices", "counts", "publications"])
    filled_publications = []
    for pub in author.get("publications", []):
        try:
            filled_publications.append(scholarly.fill(pub))
        except Exception:
            filled_publications.append(pub)
    author["publications"] = filled_publications
    publications = [normalize_publication(pub) for pub in filled_publications]
    publications.sort(key=lambda item: (item["year"], item["citations"], item["title"]), reverse=True)
    return author, publications


def write_site_data(publications: list[dict[str, Any]], profile_url: str) -> None:
    lines = [
        f"updated: {yaml_scalar(datetime.now(timezone.utc).isoformat(timespec='seconds'))}",
        f"profile: {yaml_scalar(profile_url)}",
        "items:",
    ]
    for pub in publications:
        lines.extend(
            [
                f"  - title: {yaml_scalar(pub['title'])}",
                f"    authors: {yaml_scalar(pub['authors'])}",
                f"    year: {yaml_scalar(pub['year'])}",
                f"    venue: {yaml_scalar(pub['venue'])}",
                f"    citations: {yaml_scalar(pub['citations'])}",
                f"    url: {yaml_scalar(pub['url'])}",
                f"    source: {yaml_scalar(pub['source'])}",
            ]
        )
    SITE_DATA_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_cv_tex(publications: list[dict[str, Any]]) -> None:
    lines = [
        "% This file is generated by scripts/update_scholar.py.",
        "% Edit the script or Scholar data source instead of editing this file by hand.",
        "",
        r"\begin{itemize}[leftmargin=*, itemsep=0pt]",
    ]

    if publications:
        for pub in publications:
            authors = latex_escape(pub["authors"] or "Haobo Zhao")
            year = latex_escape(pub["year"])
            title = latex_escape(pub["title"].rstrip("."))
            venue = latex_escape(pub["venue"])
            year_text = f" ({year})" if year else ""
            venue_text = f" \\textit{{{venue}}}." if venue else ""
            lines.append(f"    \\item {authors}{year_text}. \\textbf{{{title}.}}{venue_text}")
    else:
        lines.append(r"    \item Publication entries will appear here after Scholar sync.")

    lines.extend([r"\end{itemize}", ""])

    if IN_PREPARATION:
        lines.extend(
            [
                r"\subsection*{In Preparation}",
                r"\begin{itemize}[leftmargin=*, itemsep=0pt]",
            ]
        )
        for item in IN_PREPARATION:
            lines.append(f"    \\item {item}")
        lines.extend([r"\end{itemize}", ""])

    CV_TEX_PATH.write_text("\n".join(lines), encoding="utf-8")


def write_raw_json(author: dict[str, Any]) -> None:
    RAW_JSON_PATH.parent.mkdir(parents=True, exist_ok=True)
    RAW_JSON_PATH.write_text(json.dumps(author, indent=2, ensure_ascii=False, default=str), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--author-id", default=None, help="Override the Scholar author ID from _config.yml")
    parser.add_argument("--strict", action="store_true", help="Return a non-zero exit code if Scholar fetch fails")
    args = parser.parse_args()

    author_id = args.author_id or read_scholar_id()
    profile_url = f"https://scholar.google.com/citations?user={author_id}"

    try:
        author, publications = fetch_scholar(author_id)
    except Exception as exc:
        print(f"Scholar sync failed: {exc}", file=sys.stderr)
        if SITE_DATA_PATH.exists() and CV_TEX_PATH.exists() and not args.strict:
            print("Keeping existing generated publication files.", file=sys.stderr)
            return 0
        return 1

    write_site_data(publications, profile_url)
    write_cv_tex(publications)
    write_raw_json(author)
    print(f"Updated {len(publications)} Scholar publication(s) for {author_id}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
